---
- name: add key file
  apt_key: >
    id="{{ chronograf_install_apt_key_id }}"
    url="{{ chronograf_install_apt_key_url }}"
    state=present

- name: add repo
  apt_repository: >
    repo="{{ chronograf_install_apt_repository_repo }}"
    state=present
    validate_certs="{{ chronograf_install_apt_repository_validate_certs }}"

- name: install pkg
  apt: >
    name="{{ item }}"
    state=present
    update_cache="{{ chronograf_install_apt_update_cache }}"
    cache_valid_time="{{ chronograf_install_apt_cache_valid_time }}"
  with_items:
    - "{{ chronograf_install_package_list }}"
