---

- name: fail unless we run on a supported distribution
  fail: >
    msg="Unfortunately, the 'chronograf'-role is not supported on {{ ansible_distribution_release }}! :-("
  when: ansible_distribution_release|lower not in chronograf_supported_distribution_releases

- name: install apt-transport-https
  apt: >
    name=apt-transport-https
    state=present
